def main():
    protein_counts = {'A': 4, 'W': 1, 'D': 2, 'F': 2, 'S': 6, 'Stop': 3, 'P': 4, 'E': 2, 'V': 4, 'R': 6, 'M': 1, 'Q': 2, 'L': 6, 'K': 2, 'I': 3, 'C': 2, 'H': 2, 'T': 4, 'G': 4, 'N': 2, 'Y': 2}

    pre_protein = "MYCLEHEWYQHKTLDIQQAHEWNQFMWWSPIESPCAPRMPHQRTRPHLHWQECWRGHDVSAPISNKPMIQSQQSKPMCQFDQIRGYDVRGRDDYGQSWYVFDACCKIVGVQNDMDIWGMESLQVDDSHWDYEMETTHMCACFWEDHPASMVDAQELPFRITMSFRTQIPSGHMQWIIDAGDAHPCRALLEFSKFESWRNHNCEQSIPLVVSVIFIVQWEYQRFPQLGFRGMDPNKYHGNFRGAKTYRWKYTTGHLGYAPGVEQQQGNRERPWPLTFWDEKNPSKTYYFCEMVNQFVDGPEVAWVDDENVSPMIYSHICTKNRDEAWVDYLCVKNVEIWFGYGATFAYDCVHMADNQAEKMQFINPWWGPSYDTRIEAYFFLIQDQTVRACKANESFEHNNNLGDVASEGHSMCYVQQHTFLLPWMESHTFPLPHSVDNSQIPCTEGECCAGRNGHKFRDHNVLLMYNRRVSQFVPRDWTYQFWVWECLHARNFHCTRKYCWCMGDNKMEQPPPQNEIRCQDRKHCITSAYQVIFVPMTELCHEVKVREMPWHAWFRQISGNYWMMRMKAQIADFQGGTYKCMPVITLIEYIHMFLIVEEMSTVWYCHDWDTWCELHISECTDWFVGTIIMLDPAFVMDLHWMNRKPCSPSGAHIMALNWNGYAHQLDCAPGNMVPGCIIYAWDCVTYRREHLPYLSCMVSHSSACIRTFWRPGSPIYDRRHEEMIANNPLEHELQYIADFNDLKPWSPDEKPMPALKNTAQMDNDVAEQSLHEPFCPLHGVNNTTARYCAEICGVGQGGWRLKLEKLTPKALHNILRMVHINPSEYCLFWPAPVQNNNHLHAVRLQRKEFKYCTEKYPNKNMNCPCMWVDVKVTWCDPCGEQAVAELKCNWAVFKGYPYMFNWKNCIMQRTHYELISCFQGKLTNHFSKQQLDMSTTIVMYATIGPVIHQCWLNFWWTDDYSHMCLKSKSPTATVQNPLAYYMSKMRKISLSVSKNCNA"

    permutations_count = 1
    protein = list(pre_protein) + ["Stop"]
    for aa in protein:
        permutations_count *= protein_counts[aa]
        if permutations_count >= 1000000:
            permutations_count = permutations_count % 1000000
    print(permutations_count)

if __name__ == "__main__":
    main()
